
-- =============================================
-- Author:		Karl Daws
-- Created date: 4/Sep/2012
-- Description:	All Cost Reallocation reports to be based off this view
-- Uses Z_BUSINESS_RULES_HAULCYCLES to determine BUS_RULE for LU/HU hours
-- 
-- v1.1 08/Apr/2013 KDaws - Changed O61 from 'BOREFIELDS' to 'UTILS'
-- v1.2 02/Oct/2013 KDaws - Modified Anc query to include locations from EQUIP_LOCATION_TRANS. Locations are listed out
-- v1.3 26/Nov/2013 KDaws - Modified Anc query to use the last known location when no location record is found for a given status
-- v1.4 16/Dec/2013 KDaws - Added SHIFT_DATE and SHIFT_IDENT join to EST for LU & HU. Prevents statuses from previous shifts recording against a haul cycle
-- v1.5 13/Jul/2016 KDaws - Added Status Comments
-- v1.6 01/Aug/2020 KDaws - Added Sub Status to split out Tails and Sulphur Stockpile automatically
-- =============================================

CREATE VIEW [dbo].[Z_BUSINESS_RULES_HOURS]
AS


--LU's
SELECT
'LU' AS ACTIVITY_TYPE,
HCT.BUS_RULE,
HCT.HAUL_CYCLE_REC_IDENT,
HCT.LOAD_LOC,
HCT.LOAD_AREA,
HCT.MAT,
HCT.DUMP_LOC,
HCT.DUMP_AREA,
EST.EQUIP_IDENT,
EST.STATUS_CODE,
ESC.STATUS_DESC,
ESSC.SUB_STATUS_CODE,
ESSC.SUB_STATUS_DESC,
EST_CMT.EQUIP_STATUS_COMMENT,
EST.SHIFT_DATE,
EST.SHIFT_IDENT,
EST.START_TIMESTAMP,
EST.END_TIMESTAMP,
DATEDIFF(s, EST.START_TIMESTAMP, ISNULL(EST.END_TIMESTAMP, GETDATE()))/3600.0 AS DURATION_HOURS
FROM Z_BUSINESS_RULES_HAULCYCLES AS HCT
INNER JOIN WencoReport.dbo.LOAD_UNIT_STATUS_TRANS_COL AS LUST ON HCT.HAUL_CYCLE_REC_IDENT = LUST.HAUL_CYCLE_REC_IDENT
INNER JOIN WencoReport.dbo.EQUIPMENT_STATUS_TRANS AS EST ON LUST.EQUIP_STATUS_REC_IDENT = EST.EQUIP_STATUS_REC_IDENT AND HCT.DUMP_END_SHIFT_DATE = EST.SHIFT_DATE AND HCT.DUMP_END_SHIFT_IDENT = EST.SHIFT_IDENT
INNER JOIN WencoReport.dbo.EQUIP_STATUS_CODE AS ESC ON EST.STATUS_CODE = ESC.STATUS_CODE
LEFT OUTER JOIN WencoReport.dbo.EQUIP_SUB_STATUS_CODE AS ESSC ON EST.SUB_STATUS_CODE = ESSC.SUB_STATUS_CODE
LEFT OUTER JOIN WencoReport.dbo.EQUIP_STATUS_TRANS_CMT_COL AS EST_CMT ON EST.EQUIP_STATUS_REC_IDENT = EST_CMT.EQUIP_STATUS_REC_IDENT
WHERE BUS_RULE IN ('ROMBIN_FEED','DIRECT_HAUL','ROM_REHANDLE','CLEARING','HL','REHAB','OL','UTILS')
AND (((EST.STATUS_CODE LIKE 'N%' OR EST.STATUS_CODE IN ('O17','O18','O19','O20','O22','O25')) --O22 is included here because it needs to be linked with the ROM location
	AND EST.STATUS_CODE NOT IN ('N15'))
	OR (BUS_RULE IN ('ROMBIN_FEED') AND EST.STATUS_CODE IN ('N15')) --Inclusions
	OR (BUS_RULE IN ('CLEARING','REHAB') AND EST.STATUS_CODE IN ('O26')) --Inclusions
)


UNION


--HU's
SELECT
'HU' AS ACTIVITY_TYPE,
HCT.BUS_RULE,
HCT.HAUL_CYCLE_REC_IDENT,
HCT.LOAD_LOC,
HCT.LOAD_AREA,
HCT.MAT,
HCT.DUMP_LOC,
HCT.DUMP_AREA,
EST.EQUIP_IDENT,
EST.STATUS_CODE,
ESC.STATUS_DESC,
ESSC.SUB_STATUS_CODE,
ESSC.SUB_STATUS_DESC,
EST_CMT.EQUIP_STATUS_COMMENT,
EST.SHIFT_DATE,
EST.SHIFT_IDENT,
EST.START_TIMESTAMP,
EST.END_TIMESTAMP,
DATEDIFF(s, EST.START_TIMESTAMP, ISNULL(EST.END_TIMESTAMP, GETDATE()))/3600.0 AS DURATION_HOURS
FROM Z_BUSINESS_RULES_HAULCYCLES AS HCT
INNER JOIN WencoReport.dbo.HAUL_UNIT_STATUS_TRANS_COL AS HUST ON HCT.HAUL_CYCLE_REC_IDENT = HUST.HAUL_CYCLE_REC_IDENT
INNER JOIN WencoReport.dbo.EQUIPMENT_STATUS_TRANS AS EST ON HUST.EQUIP_STATUS_REC_IDENT = EST.EQUIP_STATUS_REC_IDENT AND HCT.DUMP_END_SHIFT_DATE = EST.SHIFT_DATE AND HCT.DUMP_END_SHIFT_IDENT = EST.SHIFT_IDENT
INNER JOIN WencoReport.dbo.EQUIP_STATUS_CODE AS ESC ON EST.STATUS_CODE = ESC.STATUS_CODE
LEFT OUTER JOIN WencoReport.dbo.EQUIP_SUB_STATUS_CODE AS ESSC ON EST.SUB_STATUS_CODE = ESSC.SUB_STATUS_CODE
LEFT OUTER JOIN WencoReport.dbo.EQUIP_STATUS_TRANS_CMT_COL AS EST_CMT ON EST.EQUIP_STATUS_REC_IDENT = EST_CMT.EQUIP_STATUS_REC_IDENT
WHERE BUS_RULE IN ('ROMBIN_FEED','DIRECT_HAUL','ROM_REHANDLE','CLEARING','HL','REHAB','OL','UTILS')
AND ((EST.STATUS_CODE LIKE 'N%' OR EST.STATUS_CODE IN ('O17','O18','O19','O20'))
	OR (BUS_RULE IN ('CLEARING','REHAB') AND EST.STATUS_CODE IN ('O39')) --Inclusions
)


UNION


--ANC
SELECT
ACTIVITY_TYPE,
BUS_RULE,
NULL AS HAUL_CYCLE_REC_IDENT,
CASE
	WHEN LOAD_LOC IS NULL THEN dbo.LastEquipLocation(EQUIP_IDENT,END_TIMESTAMP)	--Use last known location
	ELSE LOAD_LOC
END AS LOAD_LOC,
LOAD_AREA,
MAT,
DUMP_LOC,
DUMP_AREA,
EQUIP_IDENT,
STATUS_CODE,
STATUS_DESC,
SUB_STATUS_CODE,
SUB_STATUS_DESC,
EQUIP_STATUS_COMMENT,
SHIFT_DATE,
SHIFT_IDENT,
START_TIMESTAMP,
END_TIMESTAMP,
DURATION_HOURS
FROM (
	SELECT
	'ANC' AS ACTIVITY_TYPE,
	CASE
	WHEN EST.STATUS_CODE = 'O21' THEN 'ROMBIN_FEED'
	WHEN EST.STATUS_CODE IN ('O51','O52','O53') THEN 'REHAB'
	WHEN EST.STATUS_CODE = 'O60' AND ESSC.SUB_STATUS_CODE = '6001' THEN 'UTILS_SULPHUR' --Sulphur Stockpile
	WHEN EST.STATUS_CODE = 'O60' AND ESSC.SUB_STATUS_CODE = '6002' THEN 'OL' --Inpit Tails
	WHEN EST.STATUS_CODE = 'O60' THEN 'UTILS'
	WHEN EST.STATUS_CODE = 'O61' THEN 'UTILS' --Was 'BOREFIELDS'
	WHEN EST.STATUS_CODE = 'O70' THEN 'CLEARING'
	WHEN EST.STATUS_CODE = 'O80' THEN 'HL'
	ELSE NULL
	END AS BUS_RULE,
	STUFF((
		SELECT DISTINCT ', ' + ELT.LOCATION_NAME
		FROM WencoReport.dbo.EQUIP_LOCATION_TRANS AS ELT
		WHERE EST.EQUIP_IDENT = ELT.EQUIP_IDENT AND ELT.TIMESTAMP BETWEEN EST.START_TIMESTAMP AND EST.END_TIMESTAMP
		AND ELT.LOCATION_NAME IS NOT NULL
		FOR XML PATH('')
	),1,2, '') AS LOAD_LOC,
	'' AS LOAD_AREA,
	'' AS MAT,
	'' AS DUMP_LOC,
	'' AS DUMP_AREA,
	EST.EQUIP_IDENT,
	EST.STATUS_CODE,
	ESC.STATUS_DESC,
	ESSC.SUB_STATUS_CODE,
	ESSC.SUB_STATUS_DESC,
	EST_CMT.EQUIP_STATUS_COMMENT,
	EST.SHIFT_DATE,
	EST.SHIFT_IDENT,
	EST.START_TIMESTAMP,
	EST.END_TIMESTAMP,
	DATEDIFF(s, EST.START_TIMESTAMP, ISNULL(EST.END_TIMESTAMP, GETDATE()))/3600.0 AS DURATION_HOURS
	FROM WencoReport.dbo.EQUIPMENT_STATUS_TRANS AS EST
	INNER JOIN WencoReport.dbo.EQUIP_STATUS_CODE AS ESC ON EST.STATUS_CODE = ESC.STATUS_CODE
	LEFT OUTER JOIN WencoReport.dbo.EQUIP_SUB_STATUS_CODE AS ESSC ON EST.SUB_STATUS_CODE = ESSC.SUB_STATUS_CODE
	LEFT OUTER JOIN WencoReport.dbo.EQUIP_STATUS_TRANS_CMT_COL AS EST_CMT ON EST.EQUIP_STATUS_REC_IDENT = EST_CMT.EQUIP_STATUS_REC_IDENT
	WHERE EST.STATUS_CODE IN ('O21','O51','O52','O53','O60','O61','O70','O80')
) a